### ISSUE TITLE
Cargar combos de registro

### ISSUE THREAD

**Issue by samdsmx** [samdsmx/origen#10]
Segun los datos contenidos en la tabla "Campos" rellenar los combos del formulario.

**Comment by v1ru5tx** [comment]
Se cargo los datos para llenar en 

- Psicologico.
- Legal.
- Medico.
- Otros.
- Tipo de V.
- Modo de V.

Donde meto los campos restantes ??

**Comment by samdsmx** [comment]
Cuales son los campos restantes??

**Comment by v1ru5tx** [comment]
en la base sobran:
- CanalLegal
- ComoTeEnteraste
- Tema
-

**Comment by samdsmx** [comment]
En la pantalla de registro existe el campo: Como te enteraste.

CanaLegal va en el campo abogado (Actualmente tiene un formato de telefono)

Tema es para los organismos. (Ej. Se buscan organismos por tema, como en el video, que te mande)
