### ISSUE TITLE
Ajuste a la BD y sistema

### ISSUE THREAD

**Issue by samdsmx** [samdsmx/origen#3]
Quitar del esquema actual todas las tablas EXCEPTO:
sia_cat_actividad
sia_aso_usuario_actividad
sia_usuario
sia_persona

Para la tabla sia_persona quitar los campos FK que hacen referencia a las tablas eliminadas.

Para la tabla "sia_usuario" renombrarla por "consejeros", agregar el campo acceso de tipo int(1), renombrar el campo "usuario" y ponerle "nombre"

Modificar la aplicacion para que siga iniciando con la posibilidad de logguearse, modificar contraseña, etc.

**Comment by v1ru5tx** [comment]
Hasta este momento, la base de datos es la única cosa de este issue que he atendido :+1:

**Comment by v1ru5tx** [comment]
Pregunta: Le dejo los datos a las tablas?

**Comment by v1ru5tx** [comment]
Las tablas conservaran sus datos!?

**Comment by samdsmx** [comment]
LAs tablas que se conservan, si mantener sus datos.
