### ISSUE TITLE
Busqueda por Codigo Postal

### ISSUE THREAD

**Issue by samdsmx** [samdsmx/origen#9]
Dentro del formulario de registro de llamada, agregar la funcionalidad de cuando es una llamada nacional, poder autorellenar los campos referentes a la direccion (Estado, Municipio, Colonia) una vez ingresado el C.P. 

O bien si se selcciona un estado del combo, filtrar sus municipios y finalmente su colonia. Obteniendo a su vez el CP.

Debe permitir la captura manual en el campo colonia por si no se llegase a encontrar.

**Comment by v1ru5tx** [comment]
Oiga... tenemos el registro de la llamada o hay que hacerlo también !?

**Comment by v1ru5tx** [comment]
> O bien si se selcciona un estado del combo, filtrar sus municipios y finalmente su colonia. Obteniendo a su vez el CP. 

> Debe permitir la captura manual en el campo colonia por si no se llegase a encontrar.

De eso, si se deja la colonia a llenado manual, no sabremos el codigo postal, y al poner el CP se cambiaran todos los demas campos.

**Comment by samdsmx** [comment]
El registro de llamadas es el Issue #12 

mmm... Si actualmente no se puede hacer el llenado manual.. entonces para un futuro.. Seria poder actualizar la base CP (CRUD).. Para agregar una colonia.  Comparto video de demostracion: https://www.dropbox.com/s/68shin4qccs99f2/Direccion%20y%20Busqueda%20de%20Organismos.tvs?dl=0

(Abrir con teamviewer- Extras -  Play or Convert Record Session)

**Comment by samdsmx** [comment]
Me manda un alert con el mensaje "Error en el servidor"
